# Generated by Django 5.1.3 on 2026-06-04 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='fin_manager_user_id_37ae83_idx',
            old_name='fin_manager_user_id_date_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='fin_manager_user_id_dfa87a_idx',
            old_name='fin_manager_user_id_type_idx',
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='fin_manager_user_id_a06607_idx',
            old_name='fin_manager_user_id_cat_idx',
        ),
    ]
