# Generated by Django 5.1.3 on 2026-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_manager', '0002_rename_fin_manager_user_id_date_idx_fin_manager_user_id_37ae83_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savingsgoal',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10),
        ),
    ]
