# Generated by Django 5.1.3 on 2026-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_manager', '0003_savingsgoal_completed_date_savingsgoal_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='groq_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='groq_model',
            field=models.CharField(choices=[('llama3-70b-8192', 'Llama 3 70B (Most powerful - Recommended)'), ('llama3-8b-8192', 'Llama 3 8B (Fastest)'), ('mixtral-8x7b-32768', 'Mixtral 8x7B (Long context)'), ('gemma2-9b-it', 'Gemma 2 9B (Google)')], default='llama3-70b-8192', max_length=50),
        ),
    ]
